#  Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:
[1. Python, 2. R, 3. SQL]

**Objectives:**

{List popular languages for Data Science, python, sql, jupytel notebook, ai}

### Data Science Tools 

| Matplotlib | Pandas | NumPy |
| ------ | ------ | ------ |

### Below are a few examples of evaluating arithmetic expressions in Python

In [12]:
(3*4)+5 
#This a simple arithmetic expression to mutiply then add integers
print((3*4)+5 )

17

In [13]:
(200/60)
#This will convert 200 minutes to hours by diving by 60
print((200/60))

3.3333333333333335

## author 
Bulgansor